package com.doublefs.common.javatemplate.dao;

import com.doublefs.common.javatemplate.model.FeedConfig;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface FeedConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_config
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_config
     *
     * @mbg.generated
     */
    int insert(FeedConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_config
     *
     * @mbg.generated
     */
    FeedConfig selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_config
     *
     * @mbg.generated
     */
    List<FeedConfig> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table feed_config
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FeedConfig record);
}